version: '2'
services:
  posgresql:
    container_name: postgresql-mr
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/posgres-mr:/var/lib/postgresql
  redis:
    container_name: redis-mr
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-mr:/data
    entrypoint: redis-server --appendonly yes
