version: '2'
services:
  mysql:
    container_name: mysql-mr
    image: mysql:5.7.15
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql-mr:/var/lib/mysql/
  redis:
    container_name: redis-mr
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-mr:/data
    entrypoint: redis-server --appendonly yes
